language: python
python:
  - "3.5.2"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test questions registrationApp
  - coverage run --source=questions,registrationApp manage.py test questions registrationApp
after_success: coveralls