# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_votes_down',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_votes_up',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='pinned_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='is_made_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
