# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170403_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
