# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20170404_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pinned_by',
        ),
        migrations.AddField(
            model_name='question',
            name='button_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
