# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_remove_question_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='voted_for_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_made_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
