# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20170404_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='button_list',
        ),
        migrations.AddField(
            model_name='answer',
            name='button_up',
            field=models.ManyToManyField(related_name='button', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_py', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_made_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_made_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
