# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20170404_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='button_list',
            field=models.ManyToManyField(related_name='active_button', to=settings.AUTH_USER_MODEL),
        ),
    ]
