# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_question_button_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='button_down',
            field=models.ManyToManyField(related_name='down_button', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='button_up',
            field=models.ManyToManyField(related_name='up_button', to=settings.AUTH_USER_MODEL),
        ),
    ]
