# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20170223_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_votes',
            field=models.TextField(null=True),
        ),
    ]
