# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voters',
            field=models.ManyToManyField(related_name='voted_for_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
