# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-23 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_auto_20170323_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_to',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='uservotes',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_votes',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='voted_for_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
