# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_user_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_votes',
            field=models.TextField(default='[]'),
        ),
    ]
